name: Jira Issue PR Transition

on:
  # workflow_call is used so that this workflow may be re-used in other repositories.
  #
  # Trigger on these pull_request or pull_request_target events:
  #   [opened, closed, reopened, converted_to_draft, ready_for_review]
  #
  # (see call-jira-pr-transition for example)
  workflow_call:

jobs:
  pr-transition:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3.0.1
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Find in branch name
        id: search
        uses: atlassian/gajira-find-issue-key@v3
        with:
          string: ${{ github.head_ref }}
          from: ""
      - name: Debug
        run: |
          echo " Issue: ${{ steps.search.outputs.issue }}"
          echo "Action: ${{ github.event.action }}"
          echo "Merged: ${{ github.event.pull_request.merged }}"
          echo " Draft: ${{ github.event.pull_request.draft }}"

      - name: Transition Drafts to In Progress
        if: steps.search.outputs.issue && github.event.pull_request.draft
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.search.outputs.issue }}
          transition: "In Progress"

      - name: Transition Opened to In Review
        if: steps.search.outputs.issue && !github.event.pull_request.draft && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'ready_for_review')
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.search.outputs.issue }}
          transition: "In Review"

      - name: Transition Merged to Closed
        if: steps.search.outputs.issue && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.search.outputs.issue }}
          transition: "Closed"
